##################################################################################################
# Door bell package                                                                              #
# Version 1.1.  last changed 2019-04-22                                                         #
# Created for and tested with Home Assistant Hassio version 0.91.4                              #
# Creator Mikael Danell SHG                                                                      #
##################################################################################################

# Automation section

automation:
  - alias: "037: doorbell pressed"
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_entre_ding
        to: 'on'
    action:
       - service: notify.mobile_app_fiaiphone8
         data:
           title: 'Det plingar på dörren'
           message: 'Vill du låsa upp?'
           data:
             push:
               category: 'unlock'
       - service: notify.mobile_app_danell
         data:
           title: 'Det plingar på dörren'
           message: 'Vill du låsa upp?'
           data:
             push:
               category: 'unlock'       

  - alias: 'svar låsupp ja'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LOCK_UNLOCK_YES
    action:
      - service: lock.unlock
        data:
          code: !secret doorcode
          entity_id: lock.huvudentre