##################################################################################################
# Door bell package                                                                              #
# Version 1.0.  last changed 2018-09-21                                                          #
# Created for and tested with Home Assistant Hassio version 0.78.0                               #
# Creator Mikael Danell SHG                                                                      #
##################################################################################################

# Automation section

automation:
  - alias: "037: doorbell pressed"
    trigger:
      - platform: state
        entity_id: binary_sensor.openclose_11
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.doorbellstatus
        state: 'off'
    action:
       - service: input_boolean.turn_on
         data:
           entity_id: input_boolean.doorbellstatus
       - service: media_player.sonos_snapshot
         data:
           entity_id: media_player.home
       - service: notify.ios_sofias_iphone
         data:
           title: 'Det plingar på dörren'
           message: 'Vill du låsa upp?'
           data:
             push:
               category: 'unlock'
       - service: notify.ios_danell
         data:
           title: 'Det plingar på dörren'
           message: 'Vill du låsa upp?'
           data:
             push:
               category: 'unlock'
       - condition: time
         after: '07:30'
         before: '22:00'
       - service: media_player.volume_set
         data_template:
           entity_id: media_player.home
           volume_level: 0.5
       - service: media_player.play_media
         data:
           entity_id: media_player.home
           media_content_id: http://10.1.106.106:8123/local/doorbell-2.mp3
           media_content_type: music
       - delay: '00:00:05'
       - service: media_player.sonos_restore
         data:
           entity_id: media_player.home
           
           
           

  - alias: 'svar låsupp ja'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LOCK_UNLOCK_YES
    action:
      - service: lock.unlock
        data:
          code: 795900
          entity_id: lock.huvudentre
           
  - alias: '039: doorbell restore'
    id: '039'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.doorbellstatus
        to: 'on'
        for:
          seconds: 5
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.doorbellstatus
           
           
# Bolean section
input_boolean:
  doorbellstatus:
    name: Doorbell Pressed
    initial: off
    icon: mdi:check-outline